### ISSUE TITLE
Round border inside sexymap addon.

### ISSUE THREAD

**Issue by Azerox050** [IgorLFB/Abyss_UserInterface#5]
**Describe the bug**

**To Reproduce**
Sexymap, use square theme and AbyssUI is adding a round border inside the square frame.

**Expected behavior**
Didnt do that before, since last update.

**Screenshots**
<img width="212" alt="image" src="https://user-images.githubusercontent.com/73057449/200772443-31f30f77-2941-4f2f-ac16-43bc47b9e49c.png">

**Desktop (please complete the following information):**
W11 x64

**Comment by YugenMori** [comment]
Sorry for the late reply, I'll be updating this soon.

**Comment by YugenMori** [comment]
fixed
