### ISSUE TITLE
LUA error with bags

### ISSUE THREAD

**Issue by digitaljdr** [IgorLFB/Abyss_UserInterface#7]
LUA error when trying to open a vendor calling a backpack

Message: ...rface/AddOns/AbyssUI/functions/AbyssUI_Functions.lua:509: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Tue Aug 22 08:53:01 2023
Count: 1
Stack: ...rface/AddOns/AbyssUI/functions/AbyssUI_Functions.lua:509: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "=[C]"]: in function `GetContainerNumSlots'
[string "@Interface/AddOns/AbyssUI/functions/AbyssUI_Functions.lua"]:509: in function <...rface/AddOns/AbyssUI/functions/AbyssUI_Functions.lua:505>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by YugenMori** [comment]
which version of wow you're using? (classic, lk, retail)

**Comment by digitaljdr** [comment]
> which version of wow you're using? (classic, lk, retail)

WotLK

**Comment by YugenMori** [comment]
ok I'll check if I can replicate this.

**Comment by YugenMori** [comment]
fixed in version 10.1.5.3 (if the problem still happens, please report again)

**Comment by YugenMori** [comment]
fixed in version 10.1.5.3 (if the problem still happens, please report again)
